// AUTO-GENERATED by scan-tracks.js — do not edit by hand.
// Drop audio files into tracks/ then run:  node scan-tracks.js
export const LIBRARY = [
  {
    "id": "track-0",
    "title": "Sunrise",
    "url": "tracks/demo-1-sunrise.wav",
    "kind": "track",
    "duration": 24
  },
  {
    "id": "track-1",
    "title": "Tempo",
    "url": "tracks/demo-2-tempo.wav",
    "kind": "track",
    "duration": 24
  },
  {
    "id": "track-2",
    "title": "Cooldown",
    "url": "tracks/demo-3-cooldown.wav",
    "kind": "track",
    "duration": 24
  },
  {
    "id": "shout-3",
    "title": "Water Break",
    "url": "tracks/shoutout-water-break.mp3",
    "kind": "shoutout",
    "duration": 6.45
  }
];
