#!/usr/bin/env node
/**
 * Scans the tracks/ folder and writes js/library.js — the list of songs the DJ
 * can queue. Run this whenever you add or remove audio files:
 *
 *     node scan-tracks.js
 *
 * Naming: any file whose name starts with "shoutout" is treated as an ad/shout-out;
 * everything else is a normal track.
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const ROOT = __dirname;
const TRACKS_DIR = path.join(ROOT, "tracks");
const OUT = path.join(ROOT, "js", "library.js");
const AUDIO_EXT = new Set([".mp3", ".wav", ".m4a", ".aac", ".ogg", ".flac"]);

function prettyTitle(file) {
  return path
    .basename(file, path.extname(file))
    .replace(/^shoutout[-_ ]?/i, "")
    .replace(/^demo[-_ ]?\d*[-_ ]?/i, "")
    .replace(/^\d+[\s._-]+/, "")        // strip leading track numbers like "01 - "
    .replace(/[-_]+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase()) || path.basename(file);
}

// Pull duration + the embedded Title/Artist tags (ID3 etc.) in one ffprobe call,
// so a file named "01_track.mp3" still shows as "Eye of the Tiger — Survivor".
function probeMeta(file) {
  try {
    const out = execSync(
      `ffprobe -v error -show_entries format=duration:format_tags=title,artist -of json "${file}"`,
      { encoding: "utf8" }
    );
    const fmt = JSON.parse(out).format || {};
    const d = parseFloat(fmt.duration);
    const tags = fmt.tags || {};
    return {
      duration: Number.isFinite(d) ? Math.round(d * 100) / 100 : null,
      title: (tags.title || tags.TITLE || "").trim(),
      artist: (tags.artist || tags.ARTIST || "").trim(),
    };
  } catch {
    return { duration: null, title: "", artist: "" };
  }
}

const files = fs
  .readdirSync(TRACKS_DIR)
  .filter((f) => AUDIO_EXT.has(path.extname(f).toLowerCase()))
  .sort();

const library = files.map((f, i) => {
  const isShout = /^shoutout/i.test(f);
  const meta = probeMeta(path.join(TRACKS_DIR, f));
  // Prefer the embedded title; for songs, append the artist when we have one.
  let title = meta.title || prettyTitle(f);
  if (!isShout && meta.artist && !title.toLowerCase().includes(meta.artist.toLowerCase())) {
    title = `${title} — ${meta.artist}`;
  }
  return {
    id: (isShout ? "shout-" : "track-") + i,
    title,
    url: "tracks/" + encodeURIComponent(f),
    kind: isShout ? "shoutout" : "track",
    duration: meta.duration,
  };
});

const banner = `// AUTO-GENERATED by scan-tracks.js — do not edit by hand.
// Drop audio files into tracks/ then run:  node scan-tracks.js
`;
fs.writeFileSync(
  OUT,
  banner + "export const LIBRARY = " + JSON.stringify(library, null, 2) + ";\n"
);
console.log(`Wrote ${OUT} with ${library.length} item(s):`);
for (const t of library) console.log(`  [${t.kind}] ${t.title}  (${t.duration ?? "?"}s)`);
