#!/usr/bin/env node
/**
 * Scans the tracks/ folder and writes js/library.js — the list of songs the DJ
 * can queue. Run this whenever you add or remove audio files:
 *
 *     node scan-tracks.js
 *
 * Naming: any file whose name starts with "shoutout" is treated as an ad/shout-out;
 * everything else is a normal track.
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const ROOT = __dirname;
const TRACKS_DIR = path.join(ROOT, "tracks");
const OUT = path.join(ROOT, "js", "library.js");
const AUDIO_EXT = new Set([".mp3", ".wav", ".m4a", ".aac", ".ogg", ".flac"]);

function prettyTitle(file) {
  return path
    .basename(file, path.extname(file))
    .replace(/^shoutout[-_ ]?/i, "")
    .replace(/^demo[-_ ]?\d*[-_ ]?/i, "")
    .replace(/[-_]+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase()) || path.basename(file);
}

function probeDuration(file) {
  try {
    const out = execSync(
      `ffprobe -v error -show_entries format=duration -of default=nw=1:nk=1 "${file}"`,
      { encoding: "utf8" }
    ).trim();
    const d = parseFloat(out);
    return Number.isFinite(d) ? Math.round(d * 100) / 100 : null;
  } catch {
    return null; // ffprobe missing or unreadable — browser will learn duration at load time
  }
}

const files = fs
  .readdirSync(TRACKS_DIR)
  .filter((f) => AUDIO_EXT.has(path.extname(f).toLowerCase()))
  .sort();

const library = files.map((f, i) => {
  const isShout = /^shoutout/i.test(f);
  return {
    id: (isShout ? "shout-" : "track-") + i,
    title: prettyTitle(f),
    url: "tracks/" + encodeURIComponent(f),
    kind: isShout ? "shoutout" : "track",
    duration: probeDuration(path.join(TRACKS_DIR, f)),
  };
});

const banner = `// AUTO-GENERATED by scan-tracks.js — do not edit by hand.
// Drop audio files into tracks/ then run:  node scan-tracks.js
`;
fs.writeFileSync(
  OUT,
  banner + "export const LIBRARY = " + JSON.stringify(library, null, 2) + ";\n"
);
console.log(`Wrote ${OUT} with ${library.length} item(s):`);
for (const t of library) console.log(`  [${t.kind}] ${t.title}  (${t.duration ?? "?"}s)`);
